<?php

    function shift_cypher_menu()
    {
        $items = array();

        $items['shift_cypher'] = array(
            'title' => 'Encrypt your phrase',
            'page callback' => 'drupal_get_form',
            'page arguments' => array('shift_cypher_form'),
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM,
        );

        $items['shift_cypher_result'] = array(
            'title' => 'Here is your encryption',
            'page callback' => 'shift_cypher_result',
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
        );

        return $items;
    }

    function shift_cypher_form() {

        $form['shift_value'] = array(
            '#title' => 'Shift value',
            '#type' => 'textfield',
            '#element_validate' => array('element_validate_integer_positive'),
            '#description' => t('Enter the shift value'),
        );

        $form['direction'] = array(
            '#title' => 'Shift direction',
            '#type' => 'textfield',
            '#element_validate' => array('direction_validate'),
            '#description' => t('Enter the direction'),
        );

        $form['phrase'] = array(
            '#title' => 'Phrase',
            '#type' => 'textfield',
            '#description' => t('Enter the phrase'),
        );

        $form['submit'] = array(
            '#type' => 'submit',
            '#value' => 'Submit',
        );

        return $form;
    }

    function direction_validate($element)
   {
       $user_direction = $element['#value'];
       drupal_set_message($user_direction);
       if (($user_direction != 'Right') && ($user_direction != 'right') && ($user_direction != 'Left') && ($user_direction != 'left'))
       {
           form_error($element, t("Please enter either Left or Right"));
       }
   }

    function shift_cypher_form_submit($form, &$form_state)
    {

        $shift_value = $form_state['values']['shift_value'];
        $shift_direction = $form_state['values']['direction'];
        $phrase = $form_state['values']['phrase'];

        // make an array of letters from a-z
        $letters = range('a', 'z');

        $input_phrase_array = str_split(strtolower($phrase));

        $cypher_phrase = array();

          foreach ($input_phrase_array as $letter) {
            // if a space or punctiaton character, just push to array
            if (!in_array($letter, $letters)) {
              array_push($cypher_phrase, $letter);
            } else {
              // find the key of the letter in the letters array
              $letter_key = array_search($letter, $letters);

              if (strtolower($shift_direction) == "right") {
                $letter_key += $shift_value;

                if ($letter_key > 25) {

                  $letter_key -= 26;
                }
              }
              else {
                $letter_key -= $shift_value;
                if ($letter_key < 0) {
                  $letter_key += 26;
                }
              }
              $cypher_letter = $letters[$letter_key];

              array_push($cypher_phrase, $cypher_letter);
            }
          }

          // turn the cypher phrase array into a string and store it in the SESSION variable
         $encrypted_phrase = implode($cypher_phrase);

        $_SESSION['encoded_result'] = 'Thank you. Your shift value is ' . $shift_value . ' and your shift direction is ' . $shift_direction . '. Your encoded phrase is ' . $encrypted_phrase . '.';

        $form_state['redirect'] = 'shift_cypher_result';
    }



    function shift_cypher_result()
   {
       $answer = $_SESSION['encoded_result'];
       return $answer;
   }
